travis:
  secure:
    BINSTAR_TOKEN: Wq9fYw4rhyXMGPYoGiHG+f7iYmPe+SJPoJ4ctaz2YGMb1SWihaKJ7iVvOey9t8GHx9q5bKPAtP+4sBmaPZ4L8GWVwyfGcQEjri30W2BwCqoaQcVUo9U9FXUyblDcJkqTCtJnuxjUFz0Uo7CE1pmj1+BoSwVnfPq6LIJ4oBD03xtz3X/PRO5rzCgB0FOCKPnJBK3FtOhhU9ezQPISDnQ7JbsNYU9x561WsJYub/qdaHVwtTrNi/kxgru0R/bJIPJ8TfagmspcdsPmrOHn1UU3UgU/6UEK3pyEF5cI+X/sWWFzahuK8skInAu2djbwq9+rxzH9YsoV5KtxSkFlOQOZ0Y09yGOXNZqNQUBDGIX7lcGtXjZgtGW39Qx/yX35kllJnwiEOGInVDOPwuHNBwRjPkFopURsqFNwhteDjdegbJM/bb3i5uJBIl/Va037S+chkwEmo2DYHNmb2M9q97tRgcxEVDcmlR8EVoOfpeJRXm4dnOIoFVpYjJiHXL2N55Va04eBHJvltXlGv2lkowYiIeDGgY7ciTisznbOfRNk5mbIS9caMgENRswXuuz1Nc5HRzvw5yIyfY9aBy6Huxa8FHeku7NgiQHf8+vETj+DL6DQb856vzxXqjw+EUYkXWPCU+R7NbBc4YX8Pax4yOzgLvBuH8QqT8t+VnBP0nl8WRg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
